from pathlib import Path

MAIN = Path("src/oneblock_backend/main.mo")
WORKFLOW = Path(".github/workflows/apply-summary-cache-privacy.yml")
SELF = Path(__file__)
text = MAIN.read_text()


def replace_once(label: str, old: str, new: str) -> None:
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly one match, found {count}")
    text = text.replace(old, new, 1)


replace_once(
    "stable public summaries",
    "    var stableDerivedSummaries : [(Text, DerivedSummary)] = [];\n",
    "    var stableDerivedSummaries : [(Text, DerivedSummary)] = [];\n    var stablePublicDerivedSummaries : [(Text, DerivedSummary)] = [];\n",
)

replace_once(
    "transient public summaries",
    '''    transient var derivedSummaries = TrieMap.TrieMap<Text, DerivedSummary>(Text.equal, Text.hash);\n    derivedSummaries := TrieMap.fromEntries<Text, DerivedSummary>(Iter.fromArray(stableDerivedSummaries), Text.equal, Text.hash);\n''',
    '''    transient var derivedSummaries = TrieMap.TrieMap<Text, DerivedSummary>(Text.equal, Text.hash);\n    derivedSummaries := TrieMap.fromEntries<Text, DerivedSummary>(Iter.fromArray(stableDerivedSummaries), Text.equal, Text.hash);\n    transient var publicDerivedSummaries = TrieMap.TrieMap<Text, DerivedSummary>(Text.equal, Text.hash);\n    publicDerivedSummaries := TrieMap.fromEntries<Text, DerivedSummary>(Iter.fromArray(stablePublicDerivedSummaries), Text.equal, Text.hash);\n''',
)

replace_once(
    "preupgrade public summaries",
    "        stableDerivedSummaries := Iter.toArray(derivedSummaries.entries());\n",
    "        stableDerivedSummaries := Iter.toArray(derivedSummaries.entries());\n        stablePublicDerivedSummaries := Iter.toArray(publicDerivedSummaries.entries());\n",
)

replace_once(
    "postupgrade public summary migration",
    '''        stableProfileActivityIndex := [];\n        stableDerivedSummaries := [];\n        stableIdentityGraphs := [];\n''',
    '''        stableProfileActivityIndex := [];\n        stableDerivedSummaries := [];\n\n        // One-time compatibility migration for deployments created before the\n        // visibility-separated public summary cache existed. Future upgrades\n        // restore this cache directly from stablePublicDerivedSummaries.\n        if (Iter.size(publicDerivedSummaries.entries()) == 0) {\n            for (record in activityRecordsMap.vals()) {\n                if (record.visibility == #global) {\n                    let key = record.profile_id # ":" # record.app_id # ":" # record.activity_type;\n                    let existing = publicDerivedSummaries.get(key);\n                    let (prevCount, prevTotal, prevCurrency) = switch (existing) {\n                        case null { (0, null, record.currency) };\n                        case (?summary) { (summary.record_count, summary.total_amount, summary.currency) };\n                    };\n                    let nextTotal : ?Float = switch (record.amount) {\n                        case null { prevTotal };\n                        case (?amount) {\n                            switch (prevTotal) {\n                                case null { ?amount };\n                                case (?total) { ?(total + amount) };\n                            }\n                        };\n                    };\n                    let lastUpdated = switch (existing) {\n                        case null { record.ingest_timestamp };\n                        case (?summary) {\n                            if (record.ingest_timestamp > summary.last_updated) { record.ingest_timestamp } else { summary.last_updated }\n                        };\n                    };\n                    publicDerivedSummaries.put(key, {\n                        profile_id = record.profile_id;\n                        app_id = record.app_id;\n                        activity_type = record.activity_type;\n                        record_count = prevCount + 1;\n                        total_amount = nextTotal;\n                        currency = prevCurrency;\n                        last_updated = lastUpdated;\n                    })\n                }\n            }\n        };\n        stablePublicDerivedSummaries := [];\n        stableIdentityGraphs := [];\n''',
)

replace_once(
    "rename public summaries",
    '''                                for ((oldSummaryKey, summary) in Iter.toArray(derivedSummaries.entries()).vals()) {\n                                    if (summary.profile_id == oid) {\n                                        let newSummaryKey = nid # ":" # summary.app_id # ":" # summary.activity_type;\n                                        derivedSummaries.put(newSummaryKey, { summary with profile_id = nid });\n                                        ignore derivedSummaries.remove(oldSummaryKey);\n                                    }\n                                };\n\n                                ignore profiles.remove(oid);\n''',
    '''                                for ((oldSummaryKey, summary) in Iter.toArray(derivedSummaries.entries()).vals()) {\n                                    if (summary.profile_id == oid) {\n                                        let newSummaryKey = nid # ":" # summary.app_id # ":" # summary.activity_type;\n                                        derivedSummaries.put(newSummaryKey, { summary with profile_id = nid });\n                                        ignore derivedSummaries.remove(oldSummaryKey);\n                                    }\n                                };\n                                for ((oldSummaryKey, summary) in Iter.toArray(publicDerivedSummaries.entries()).vals()) {\n                                    if (summary.profile_id == oid) {\n                                        let newSummaryKey = nid # ":" # summary.app_id # ":" # summary.activity_type;\n                                        publicDerivedSummaries.put(newSummaryKey, { summary with profile_id = nid });\n                                        ignore publicDerivedSummaries.remove(oldSummaryKey);\n                                    }\n                                };\n\n                                ignore profiles.remove(oid);\n''',
)

replace_once(
    "submit public summary",
    '''        derivedSummaries.put(sKey, {\n            profile_id = newRecord.profile_id;\n            app_id = newRecord.app_id;\n            activity_type = newRecord.activity_type;\n            record_count = prevCount + 1;\n            total_amount = newTotal;\n            currency = prevCurrency;\n            last_updated = now\n        });\n        #ok(recordId)\n''',
    '''        derivedSummaries.put(sKey, {\n            profile_id = newRecord.profile_id;\n            app_id = newRecord.app_id;\n            activity_type = newRecord.activity_type;\n            record_count = prevCount + 1;\n            total_amount = newTotal;\n            currency = prevCurrency;\n            last_updated = now\n        });\n\n        // Maintain a second aggregate containing public evidence only. This keeps\n        // public summary reads O(1) without allowing private counts/amounts to leak.\n        if (newRecord.visibility == #global) {\n            let publicExisting = publicDerivedSummaries.get(sKey);\n            let (publicPrevCount, publicPrevTotal, publicPrevCurrency) = switch (publicExisting) {\n                case null { (0, null, newRecord.currency) };\n                case (?summary) { (summary.record_count, summary.total_amount, summary.currency) };\n            };\n            let publicNewTotal : ?Float = switch (newRecord.amount) {\n                case null { publicPrevTotal };\n                case (?amount) {\n                    switch (publicPrevTotal) {\n                        case null { ?amount };\n                        case (?total) { ?(total + amount) };\n                    }\n                };\n            };\n            publicDerivedSummaries.put(sKey, {\n                profile_id = newRecord.profile_id;\n                app_id = newRecord.app_id;\n                activity_type = newRecord.activity_type;\n                record_count = publicPrevCount + 1;\n                total_amount = publicNewTotal;\n                currency = publicPrevCurrency;\n                last_updated = now\n            })\n        };\n        #ok(recordId)\n''',
)

old_summary = '''    // Summaries are computed from the caller-visible record set so private records\n    // cannot leak through aggregate counts or amounts. The write-side summary map is\n    // retained as a cache for future internal use, but is not exposed directly.\n    public query ({ caller }) func getDerivedSummary(\n        profileId : ProfileId,\n        appId : AppId,\n        activityType : ActivityTypeKey\n    ) : async ?DerivedSummary {\n        let profile = switch (profiles.get(profileId)) {\n            case null { return null };\n            case (?profile) { profile };\n        };\n        let ids = switch (profileActivityIndex.get(profileId)) {\n            case null { return null };\n            case (?ids) { ids };\n        };\n\n        var recordCount : Nat = 0;\n        var totalAmount : ?Float = null;\n        var currency : ?Text = null;\n        var currencyInitialized = false;\n        var lastUpdated : Int = 0;\n\n        for (rid in ids.vals()) {\n            switch (activityRecordsMap.get(rid)) {\n                case null {};\n                case (?record) {\n                    if (\n                        record.app_id == appId and\n                        record.activity_type == activityType and\n                        canReadActivityRecord(caller, profile, record)\n                    ) {\n                        recordCount += 1;\n                        switch (record.amount) {\n                            case null {};\n                            case (?amount) {\n                                totalAmount := switch (totalAmount) {\n                                    case null { ?amount };\n                                    case (?total) { ?(total + amount) };\n                                }\n                            };\n                        };\n                        if (not currencyInitialized) {\n                            currency := record.currency;\n                            currencyInitialized := true\n                        };\n                        if (record.ingest_timestamp > lastUpdated) {\n                            lastUpdated := record.ingest_timestamp\n                        }\n                    }\n                };\n            }\n        };\n\n        if (recordCount == 0) {\n            null\n        } else {\n            ?{\n                profile_id = profileId;\n                app_id = appId;\n                activity_type = activityType;\n                record_count = recordCount;\n                total_amount = totalAmount;\n                currency = currency;\n                last_updated = lastUpdated;\n            }\n        }\n    };\n'''
new_summary = '''    // Keep summary reads O(1) while preserving visibility: owners read the full\n    // aggregate; everyone else reads the global-only aggregate.\n    public query ({ caller }) func getDerivedSummary(\n        profileId : ProfileId,\n        appId : AppId,\n        activityType : ActivityTypeKey\n    ) : async ?DerivedSummary {\n        switch (profiles.get(profileId)) {\n            case null { null };\n            case (?profile) {\n                let key = summaryKey(profileId, appId, activityType);\n                if (caller == profile.owner) {\n                    derivedSummaries.get(key)\n                } else {\n                    publicDerivedSummaries.get(key)\n                }\n            };\n        }\n    };\n'''
replace_once("O1 summary read", old_summary, new_summary)

MAIN.write_text(text)
if WORKFLOW.exists():
    WORKFLOW.unlink()
SELF.unlink()
